### ISSUE TITLE
The comparisons should also be available in Python

### ISSUE THREAD

**Issue by zhaofeng-shu33** [plaveczlambert/deep_euler_tests#1]
There are lots of IO operations in computation. So I think it is fair to compare the performance of DEM with Euler method in current
implementation.

**Comment by plaveczlambert** [comment]
The point of these tests is not measuring the actual speed of computation. The point is creating plots on which a visual assessment of the Deep Euler and Euler methods can be made. As such it cannot be unfair, since the resulting plots have nothing to do with the performance of the generating codes, the used language, the number of IO operations etc. It is true that the current C++ code has an unnecessary number of IO operations, and it may seem harder to use the Deep Euler Method because of it. However the C++ codes will remain, because my aim is to use DEM on a complex differential equation with matrix-vector multiplications in it, which will certainly run faster in C++ than in Python. 
I will update the Readme file to clarify that:
1. The codes are not for testing the speed of computation, they are for testing the integration performance
2. The C++ codes demonstrate the viability of using DEM in C++,  but they are far from optimized.

**Comment by zhaofeng-shu33** [comment]
If only the solution is considered regardless of the computational cost, I think it can be implemented directly in Python. I have
made [this attempt](https://github.com/zhaofeng-shu33/deep_euler_tests/blob/main/Lotka/DEM.py).

**Comment by plaveczlambert** [comment]
Yes, I absolutely agree that it would be better, much more user-friendly to be able to run the tests in Python, too. But currently it is no priority. It is also impossible to merge your implementation into this repo, as you have changed a lot of things that are obviously incompatible with my implementation. Nevertheless, thank you for the suggestion, if I get some spare time, I will implement a Python test. Your implementation will definitely make a good starting point.
I leave this issue open, in order to remember it.

**Comment by zhaofeng-shu33** [comment]
Thanks for your information. I have checked your published paper on arxiv. It seems that you focus on applying HPC optimization techniques to ODE solvers. I did research on applying Neural network techniques to boost ODE solvers.

**Comment by plaveczlambert** [comment]
The Euler and Deep Euler methods are now available in Python, no need to use the C++ codes for the ODE solutions. I also updated the readme file to recommend using the Python codes.
